#!/usr/bin/env bash
# copy

#!/usr/bin/env bash
# copy
b=4
if [ $# -lt $b ]
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
        scp -i $4 "$1" "$3"@"$2":~
fi
