#!/usr/bin/env bash
# Install nginx on HAProxy loadBalancer
# Ensure script is run as root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

apt-get install -y --no-install-recommends software-properties-common
echo | add-apt-repository -y ppa:vbernat/haproxy-1.6.3
apt-get install -y haproxy=1.6.3
FILE_PATH='/etc/haproxy/haproxy.cfg'
# 54.159.28.29 LOAD BALANCER
# 34.204.81.253:80 WEB-SERVER 1
# 52.87.154.218:80 WEB-SERVER 2
# string="frontend WEBS\n\tbind 34.204.81.253:80\n\tbind 52.87.154.218:80"
frontend="frontend WEBS\n\tbind  54.159.28.29:80\n\tdefault_backend SERVERS\n"
backend="backend SERVERS\n\tbalance roundrobn\n\tserver web-01 34.204.81.253:80 check\n\tserver web-02 52.87.154.218:80 check\n"
if ! grep -q "$frontend" "$FILE_PATH" ; then
    # Backup the original file
    cp "$FILE_PATH" "${FILE_PATH}.bak"
    echo -e "$frontend" >> "$FILE_PATH"
    #restart HAPROXY
    service haproxy restart
fi
if ! grep -q "$backend" "$FILE_PATH" ; then
    # Backup the original file
    cp "$FILE_PATH" "${FILE_PATH}.bak"
    echo -e "$backend" >> "$FILE_PATH"
    #restart HAPROXY
    service haproxy restart
fi
