#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
replacement_str="location /redirect_me {\n        return 301 https://www.example1.com/new_page;\n    }"
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
# Configure nginx to listen on port 80 and serve "Hello World!" at the root
sed -i "/^}/i \\n/$replacement_str" /etc/nginx/sites-available/default

# Restart nginx
service nginx restart