#!/usr/bin/env bash
#Configure a new Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i '/^\s*location \/ {/{
    N
    N
    s/^\s*location \/ {\n\s*try_files \$uri \$uri\/ =404;\n\s*}/    location \/redirect_me {\n        return 301 https:\/\/www.example.com\/new_page;\n    }/;
}' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee index.nginx-debian.html
sudo service nginx restart