#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get update
apt-get -y install nginx
replacement_str="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
not_found="Ceci n'est pas une page."
ufw allow 'Nginx HTTP'
# Configure nginx to listen on port 80 and serve "Hello World!" at the root
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/^}/i \\\n$replacement_str" /etc/nginx/sites-available/default

sed -i "s/try_files \$uri \$uri/ =404; =404;/try_files / $not_found;/g" /etc/nginx/sites-available/default
# Restart nginx
service nginx restart

