#!/usr/bin/env bash
# Install and configure HAProxy as a load balancer for two web servers

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit
fi

# Add HAProxy repository and install HAProxy
sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get install -y haproxy=2.8.*

# Configure HAProxy
FILE_PATH='/etc/haproxy/haproxy.cfg'
sudo chown $USER:$USER $FILE_PATH

frontend="frontend WEBS\n\tbind *:80\n\tmode http\n\tdefault_backend SERVERS\n"
backend="backend SERVERS\n\tmode http\n\tbalance roundrobin\n\toption forwardfor\n\thttp-request set-header X-Forwarded-Port %[dst_port]\n\tserver web-01 34.204.81.253:80 check\n\tserver web-02 52.87.154.218:80 check\n"

# Check if HAProxy is already running
if pgrep haproxy > /dev/null; then
    sudo service haproxy restart
else
    sudo service haproxy start
fi

# Write frontend and backend configurations to HAProxy config file
echo -e "$frontend" | sudo tee -a $FILE_PATH > /dev/null
echo -e "$backend" | sudo tee -a $FILE_PATH > /dev/null
