#!/usr/bin/env bash
# This script configures HAProxy to distribute traffic to two web servers using round-robin algorithm

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
    balance roundrobin
    server 312646-web-01 34.204.81.253:80 check
    server 312646-web-02 52.87.154.218:80 check
EOF

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy
