#!/usr/bin/env bash
# Install nginx on HAProxy loadBalancer
# Ensure script is run as root
# if [ "$EUID" -ne 0 ]
#   then echo "Please run as root"
#   exit
# fi

sudo apt-get install -y --no-install-recommends software-properties-common
echo | add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\* 
# sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg
sudo service enable haproxy
FILE_PATH='/etc/haproxy/haproxy.cfg'
# 54.159.28.29 LOAD BALANCER
# 34.204.81.253:80 WEB-SERVER 1
# 52.87.154.218:80 WEB-SERVER 2
# string="frontend WEBS\n\tbind 34.204.81.253:80\n\tbind 52.87.154.218:80" 10.247.67.64
frontend="frontend WEBS\n\tbind  *:80\n\tmode http\n\tdefault_backend SERVERS\n"
backend="backend SERVERS
\tmode http
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\tserver 312646-web-01 34.204.81.253:80 check
\tserver 312646-web-02 52.87.154.218:80 check
"
echo -e "$frontend" >> "$FILE_PATH"
echo -e "$backend" >> "$FILE_PATH"
if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi

