#!/usr/bin/env bash
# This script checks and fixes Nginx installaon Ubuntu to ensure it listens on port 80
sudo apt-get install -y nginx -qq > /dev/null
echo "hey" | tee /var/run/nginx.pid > /run/nginx.pid

