#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd

# Read the file line by line using a while loop
while IFS=: read -r user_name user_password user_id group_id user_info home_directory shell; do
     # Display the required information
    echo "The user $user_name is part of the $group_id gang, lives in $home_directory and rides $shell. $user_id place is protected by the passcode $user_password, more info about the user here:  $user_info"
done < /etc/passwd
