#!/usr/bin/env bash
# Bash script to display visitor IP along with HTTP status code from Apache log file

# Check if apache-access.log exists
log_file="apache-access.log"
if [ ! -f "$log_file" ]; then
    exit 1
fi

# Use awk to extract and display IP and HTTP status code
awk '
{
    arr[$1]++
    status_field[$1] = $9
}
END {
    for (i in arr) 
        print arr[i], i, status_field[i]
}
' "$log_file" | sort -n -r

