#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
#Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i '1i\
127.0.0.1 localhost\
facebook.com 8.8.8.8' ~/hosts.new
# echo "127.0.0.1        codespaces-a21a68" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new

