#!/usr/bin/env bash
# debugging
# apt-get update
# apt-get -y install apache2
# apt-get update
# apt-get -y install apache2-utils
# # rapt install -y tcl
# starts apache2
service apache2 start
# echo "Hello Holberton" > /usr/local/apache2/htdocs
